* Introduction

This document is a step by step guide showing how to configure emacspeak on a mac.  It includes installation of emacs, emacspeak and the e-mac-server.

These instructions are only one way to achieve the end result of having emacspeak working on a mac.  This is the way I found worked best for me.  For example I have chosen to use "brew" to install emacs, I had no luck with the seemingly popular "macports".  Your mileage may vary.


I have also made assumptions about file paths, feel free to put things where it feels most comfortable.  

I welcome any updates to this document and or questions or issues found when following these instructions.

* Prerequisites

- A mac running a recent version of os x.  I used snow leopard 10.6.7.
- An internet connection so we can download all the required bits.



The version of emacs shipped with snow leopard (22.1) is not recent enough.  We will be installing emacs 24.  It also appears that the emacs shipped with snow leopard only runs in the terminal and not as a standalone app. 


* XCODE4 
To be able to build packages using homebrew you will need to have apple xcode installed.  If you are an apple developer it is a free download or can be purchased for around $5 from the mac appstore if you are not.

It can be installed from the mac app store.

Here is a link to the relevant apple developer page:
http://developer.apple.com/xcode/

It is a rather large download of about 4 gig so may take some time to install depending on your Internet connection speed.


* Homebrew

Homebrew is a package management system for installing unix programs on mac.  You can read all about it at the below URL or the blog post sighted in the following text: 
https://github.com/mxcl/homebrew

These instructions are mostly taken from the blog post at:
http://www.engineyard.com/blog/2010/homebrew-os-xs-missing-package-manager/


To install homebrew, from the terminal run the following commands.  I suggest that if you are at all worried checkout the script that is being run by the curl command so as to not install anything on your system that may be in any way suspicious  .

#Note: I had to create the /usr/local directory on my mac which isn't in the blog post.
# create /usr/local if it doesn't already exist
sudo mkdir -p /usr/local
# Take ownership of /usr/local so you don't have to sudo
sudo chown -R `whoami` /usr/local
# Fix the permissions on your mysql installation, if you have one
sudo chown -R mysql:mysql /usr/local/mysql*
# Download and install Homebrew from github
curl -L http://github.com/mxcl/homebrew/tarball/master | tar xz --strip 1 -C /usr/local

Once this is complete you should now have the "brew" program in your path.

If typing "brew" at the terminal prompt gives a "command not found" error investigate if "/usr/local/bin" is in your PATH environment variable.

If everything has worked up to this point typing "brew" should display an example usage message.

* Install git

Next we will install git as it is required to be able to update homebrew itself as well as to install many homebrew formula.

From the terminal:

brew install git

* Install emacs

This installs the current development branch of emacs24 from  repo.or.cz.

It may be possible to use other emacson such as aquamax or other distributions specifically for the mac.  I had no luck doing so and this was the way that worked for me.

If anyone else is using a different emacs I would love to hear about it so I can add aditional install options here.

To install using brew, issue the following command from the terminal: 
brew install emacs --HEAD --use-git-head --cocoa

You will need to have added /usr/local/bin to the beginning of your PATH environment variable otherwise the shell will find the apple supplied version of emacs.

You can check this has worked by issueing the following command at the terminal:

which emacs

It should report /usr/local/bin/emacs 


* Install emacspeak

We will keep emacspeak in a directory ~/src/emacspeak
# create the ~/src dir if it doesn't exist
mkdir -p ~/src
# changedir to ~/src
cd ~/src
# checkout a copy of emacspeak from the google svn repository
svn co http://emacspeak.googlecode.com/svn/trunk emacspeak

cd emacspeak
make config
make emacspeak


* Test the e-mac-speak server

Before trying to run emacspeak itself we need to verify that the e-mac-speak server is working.

To do this, from the terminal:

# Change to the emacspeak servers directory
cd ~/src/emacspeak/servers
# run the e-mac-speak server
./mac

At this point you should hear the words "emacspeak server" spoken.

If not then we have a problem.

To speak some text enter the following lines.

q {This is a test.}
d

You should hear the words "This is a test."

If all goes well move on to the next step.  If not troubleshoot the issue until the above steps work.
 
* Emacs initialization

To get emacs to start up loading emacspeak with the e-mac-speak server place the following in your .emacs.d/init.el file.

This is the minimum required to ensure that emacspeak comes up talking.  You will want to investigate further customizations of both emacs and emacspeak as you progress.

A good place to look for emacspeak customizations is in the "tvr" directory of the emacspeak source.  This is Raman's emacs customizations.


fixme
